### ISSUE TITLE
Spent time calculation is wrong when remaining time is adjusted

### ISSUE THREAD

**Issue by atrhesehus** [hesehus/jira-time#59]
In the attached example Jira-time shows 4h estimated, 2.8h remaining, which is correct. The progress indicator shows 30 % spent which is incorrect.

Jira has the correct numbers which are: 4h estimated, 2.8h remaining, 9h 8m logged. So in fact more than 200 % of the original time has been spent.

![jiratime-issue](https://cloud.githubusercontent.com/assets/28297952/25616512/8238e690-2f3d-11e7-966a-b55136790a48.png)

![jira-hours](https://cloud.githubusercontent.com/assets/28297952/25616556/c9250110-2f3d-11e7-839c-41bd94b510b9.png)

**Comment by hkhesehus** [comment]
The bar displays the difference between the original and remaining estimate, and cannot be compared with how Jira displays the numbers. I propose that we change it so that we show 2 bars, like Jira also does some times (see attachment)
<img width="197" alt="jira-bar" src="https://cloud.githubusercontent.com/assets/18420855/25634525/43d4ea78-2f7b-11e7-85f1-4d288edb4563.png">

**Comment by atrhesehus** [comment]
I would expect percent spent to be logged hours compared to estimated hours. In my example we spent 228 % of the available hours. In that case you could show the progress bar full and in a red color to indicate that it is >100 %.

**Comment by hkhesehus** [comment]
Implemented the proposed example with two bars.
The top one indicates the original estimate
The bottom shows the time spent / remaining estimate.

**Comment by hakonhk** [comment]
@atrhesehus This is ready for test now!
